# Generated by Django 4.0 on 2021-12-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2_rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
